# Generated by Django 5.1.3 on 2024-12-04 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STIWEBSERVICE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='STIWEBSERVICE.departamento'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
