# Generated by Django 5.0.2 on 2024-12-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STIWEBSERVICE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='departamento',
            field=models.CharField(max_length=200),
        ),
    ]
