# Generated by Django 5.0.2 on 2024-12-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STIWEBSERVICE', '0002_alter_ticket_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='departamento',
        ),
    ]
