# Generated by Django 5.1.3 on 2024-12-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STIWEBSERVICE', '0004_alter_asignacion_asignado_a_alter_ticket_prioridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='visita_terreno',
            field=models.BooleanField(default=False),
        ),
    ]
