# Generated by Django 5.1.3 on 2024-12-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STIWEBSERVICE', '0005_ticket_visita_terreno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
